package org.sodsat.expertsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DailyReadings implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Date of the leaf wetness readings     aaaa")
   private java.util.Date readingsDate;
   @org.kie.api.definition.type.Description("List of sensor readings for the current date")
   @org.kie.api.definition.type.Label("Reading values of the day")
   private java.util.List<java.lang.Double> readingValues;

   public DailyReadings()
   {
   }

   public java.util.Date getReadingsDate()
   {
      return this.readingsDate;
   }

   public void setReadingsDate(java.util.Date readingsDate)
   {
      this.readingsDate = readingsDate;
   }

public java.util.List<java.lang.Double> getReadingValues()
   {
      return this.readingValues;
   }

   public void setReadingValues(java.util.List<java.lang.Double> readingValues)
   {
      this.readingValues = readingValues;
   }

   public DailyReadings(java.util.Date readingsDate,
         java.util.List<java.lang.Double> readingValues)
   {
      this.readingsDate = readingsDate;
      this.readingValues = readingValues;
   }

   /*Method to fill in an array with daily leaf wetness values*/
   public void initDailyLeafWetnessReadings()
   {
      // Today's date.
      this.readingsDate = new java.util.Date();
      // List of readings.
      this.readingValues = new java.util.ArrayList<Double>();
      this.readingValues.add(100.0); // 	1 hour with wet leaf (pos 0)
      this.readingValues.add(100.0); // 	2 hours with wet leaf (pos 1)
      this.readingValues.add(100.0); // 	3 hours with wet leaf (pos 2)
      this.readingValues.add(100.0); // 	4 hours with wet leaf (pos 3)
      this.readingValues.add(100.0); // 	5 hours with wet leaf (pos 4)
      this.readingValues.add(100.0); // 	6 hours with wet leaf (pos 5)
      this.readingValues.add(100.0); // 	7 hours with wet leaf (pos 6)
      this.readingValues.add(100.0); // 	8 hours with wet leaf (pos 7)
      this.readingValues.add(100.0); // 	9 hours with wet leaf (pos 8)
      this.readingValues.add(100.0); // 	10 hours with wet leaf (pos 9)
      this.readingValues.add(100.0); // 	11 hours with wet leaf (pos 10)
   }

   /*Method to fill in an array with daily air temperature values*/
   public void initDailyAirTempReadings()
   {
      // Today's date.
      this.readingsDate = new java.util.Date();
      // List of readings.
      this.readingValues = new java.util.ArrayList<Double>();
      this.readingValues.add(18.0);	// Air Temperature 1 (pos 0)
      this.readingValues.add(24.0);	// Air Temperature 2 (pos 1)
      this.readingValues.add(30.0);	// Air Temperature 3 (pos 2)
      this.readingValues.add(33.0);	// Air Temperature 4 (pos 3)
      this.readingValues.add(10.0);	// Air Temperature 5 (pos 4)
   }

   /*Method to fill in an array with daily soil temperature values*/
   public void initDailySoilTempReadings()
   {
      // Today's date.
      this.readingsDate = new java.util.Date();

      // List of readings.
      this.readingValues = new java.util.ArrayList<Double>();
      this.readingValues.add(20.0);	// Soil Temperature 1 (pos 0)
      this.readingValues.add(17.0);	// Soil Temperature 2 (pos 1)
      this.readingValues.add(19.0);	// Soil Temperature 3 (pos 2)
      this.readingValues.add(18.0);	// Soil Temperature 4 (pos 3)
   }
}