package org.sodsat.expertsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Irrigation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description("Comes from Soil Sensor")
   @org.kie.api.definition.type.Label("Soil Water Content")
   private double soilWaterContent;
   @org.kie.api.definition.type.Description("Depends on the type of turfgrass")
   @org.kie.api.definition.type.Label("Root Depth")
   private double rootDepth;
   @org.kie.api.definition.type.Description("Depends on the soil type")
   @org.kie.api.definition.type.Label("Soil Water Capacity")
   private double soilWaterCapacity;
   @org.kie.api.definition.type.Description("Set by the user")
   @org.kie.api.definition.type.Label("Confidence Threshold")
   private double confidenceThreshold;
   @org.kie.api.definition.type.Description("(availableLiters / eTt) * 24")
   @org.kie.api.definition.type.Label("Time Before Irrigation (in hours) [with user confidence threshold]")
   private double timeBeforeIrrigationThreshold;
   @org.kie.api.definition.type.Description("Evapo transpiration value of the sensor")
   @org.kie.api.definition.type.Label("ETo")
   private double eTo;
   @org.kie.api.definition.type.Description("Crop coefficient (depends on the turfgrass type)")
   @org.kie.api.definition.type.Label("Kc")
   private double kc;
   @org.kie.api.definition.type.Description("(availableWC - currentWC) * 1000")
   @org.kie.api.definition.type.Label("Amount of water to reintegrate (in liters)")
   private double waterToReintegrate;
   @org.kie.api.definition.type.Label("Time before irrigation (in hours) [without user confidence threshold]")
   private double timeBeforeIrrigation;

   @org.kie.api.definition.type.Label("Irrigation Alarm")
   private java.lang.String irrigationAlarm;

   @org.kie.api.definition.type.Description("Turfgrass species (Enum) that influences the root depth and crop coefficient")
   @org.kie.api.definition.type.Label("Turfgrass species")
   private java.lang.String turfgrassSpecies;

   @org.kie.api.definition.type.Description("Enum type indicating the composition of the soil")
   @org.kie.api.definition.type.Label("Soil Type")
   private java.lang.String soilType;

   @org.kie.api.definition.type.Label("Soil Wilting Point")
   private java.lang.Double soilWiltingPoint;

   public Irrigation()
   {
   }

   public double getSoilWaterContent()
   {
      return this.soilWaterContent;
   }

   public void setSoilWaterContent(double soilWaterContent)
   {
      this.soilWaterContent = soilWaterContent;
   }

   public double getRootDepth()
   {
      return this.rootDepth;
   }

   public void setRootDepth(double rootDepth)
   {
      this.rootDepth = rootDepth;
   }

   public double getSoilWaterCapacity()
   {
      return this.soilWaterCapacity;
   }

   public void setSoilWaterCapacity(double soilWaterCapacity)
   {
      this.soilWaterCapacity = soilWaterCapacity;
   }

   public double getConfidenceThreshold()
   {
      return this.confidenceThreshold;
   }

   public void setConfidenceThreshold(double confidenceThreshold)
   {
      this.confidenceThreshold = confidenceThreshold;
   }

   public double getTimeBeforeIrrigationThreshold()
   {
      return this.timeBeforeIrrigationThreshold;
   }

   public void setTimeBeforeIrrigationThreshold(
         double timeBeforeIrrigationThreshold)
   {
      this.timeBeforeIrrigationThreshold = timeBeforeIrrigationThreshold;
   }

   public double geteTo()
   {
      return this.eTo;
   }

   public void seteTo(double eTo)
   {
      this.eTo = eTo;
   }

   public double getKc()
   {
      return this.kc;
   }

   public void setKc(double kc)
   {
      this.kc = kc;
   }

   public double getWaterToReintegrate()
   {
      return this.waterToReintegrate;
   }

   public void setWaterToReintegrate(double waterToReintegrate)
   {
      this.waterToReintegrate = waterToReintegrate;
   }

   public double getTimeBeforeIrrigation()
   {
      return this.timeBeforeIrrigation;
   }

   public void setTimeBeforeIrrigation(double timeBeforeIrrigation)
   {
      this.timeBeforeIrrigation = timeBeforeIrrigation;
   }

   public java.lang.String getIrrigationAlarm()
   {
      return this.irrigationAlarm;
   }

   public void setIrrigationAlarm(java.lang.String irrigationAlarm)
   {
      this.irrigationAlarm = irrigationAlarm;
   }

   public java.lang.String getTurfgrassSpecies()
   {
      return this.turfgrassSpecies;
   }

   public void setTurfgrassSpecies(java.lang.String turfgrassSpecies)
   {
      this.turfgrassSpecies = turfgrassSpecies;
   }

   public java.lang.String getSoilType()
   {
      return this.soilType;
   }

   public void setSoilType(java.lang.String soilType)
   {
      this.soilType = soilType;
   }

   public java.lang.Double getSoilWiltingPoint()
   {
      return this.soilWiltingPoint;
   }

   public void setSoilWiltingPoint(java.lang.Double soilWiltingPoint)
   {
      this.soilWiltingPoint = soilWiltingPoint;
   }

   public Irrigation(double soilWaterContent, double rootDepth,
         double soilWaterCapacity, double confidenceThreshold,
         double timeBeforeIrrigationThreshold, double eTo, double kc,
         double waterToReintegrate, double timeBeforeIrrigation,
         java.lang.String irrigationAlarm, java.lang.String turfgrassSpecies,
         java.lang.String soilType, java.lang.Double soilWiltingPoint)
   {
      this.soilWaterContent = soilWaterContent;
      this.rootDepth = rootDepth;
      this.soilWaterCapacity = soilWaterCapacity;
      this.confidenceThreshold = confidenceThreshold;
      this.timeBeforeIrrigationThreshold = timeBeforeIrrigationThreshold;
      this.eTo = eTo;
      this.kc = kc;
      this.waterToReintegrate = waterToReintegrate;
      this.timeBeforeIrrigation = timeBeforeIrrigation;
      this.irrigationAlarm = irrigationAlarm;
      this.turfgrassSpecies = turfgrassSpecies;
      this.soilType = soilType;
      this.soilWiltingPoint = soilWiltingPoint;
   }

}