package org.sodsat.expertsystem;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Treatment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Description(value = "Fungi for which the treatment is effective (enum)")
   @org.kie.api.definition.type.Label(value = "Fungi Treatment")
   private java.lang.String fungiTreatment;
   @org.kie.api.definition.type.Description(value = "Treatment concentration in commercial products")
   @org.kie.api.definition.type.Label(value = "Concentration (%)")
   private java.lang.Double concentration;
   @org.kie.api.definition.type.Description(value = "Application rate of the treatmener")
   @org.kie.api.definition.type.Label(value = "Dosage (L/ha)")
   private java.lang.Double applicationRate;
   @org.kie.api.definition.type.Description(value = "Fungi species to treat (enum)")
   @org.kie.api.definition.type.Label(value = "Fungi species")
   private java.lang.String fungiSpecies;

   public Treatment()
   {
   }

   public java.lang.String getFungiTreatment()
   {
      return this.fungiTreatment;
   }

   public void setFungiTreatment(java.lang.String fungiTreatment)
   {
      this.fungiTreatment = fungiTreatment;
   }

   public java.lang.Double getConcentration()
   {
      return this.concentration;
   }

   public void setConcentration(java.lang.Double concentration)
   {
      this.concentration = concentration;
   }

   public java.lang.Double getApplicationRate()
   {
      return this.applicationRate;
   }

   public void setApplicationRate(java.lang.Double applicationRate)
   {
      this.applicationRate = applicationRate;
   }

   public java.lang.String getFungiSpecies()
   {
      return this.fungiSpecies;
   }

   public void setFungiSpecies(java.lang.String fungiSpecies)
   {
      this.fungiSpecies = fungiSpecies;
   }

   public Treatment(java.lang.String fungiTreatment,
         java.lang.Double concentration, java.lang.Double applicationRate,
         java.lang.String fungiSpecies)
   {
      this.fungiTreatment = fungiTreatment;
      this.concentration = concentration;
      this.applicationRate = applicationRate;
      this.fungiSpecies = fungiSpecies;
   }

}